version: '2.1'
networks: {}
volumes:
    resin-data: {}
services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - resin-data:/var/www/html/storage/upload
    environment:
      - APP_ENV=local
      - APP_KEY=SomeRandomStringOf32CharsExactly
      - APP_URL=https://firefly.example.com
      - TRUSTED_PROXIES=**
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=secret_firefly_password
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    # https://hub.docker.com/r/yobasystems/alpine-mariadb
    image: yobasystems/alpine-mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: firefly
      MYSQL_USER: firefly
      MYSQL_PASSWORD: secret_firefly_password
      MARIADB_ROOT_PASSWORD: my-secret-pw
    expose:
    - 3306
    volumes:
      - resin-data:/var/lib/mysql
      - resin-data:/var/lib/mysql/mysql-bin
